templ = ['[{sip}]',
         'fullname =',
         'registersip = no',
         'host = dynamic',
         'callgroup = 1',
         'mailbox = {sip}',
         'call-limit = 100',
         'type = peer',
         'username = {sip}',
         'transfer = yes',
         '\n',
         'callcounter = yes',
         'context = DLPN_DialPlan1',
         'cid_number = {sip}',
         'hasvoicemail = no',
         'vmsecret =',
         'email =',
         'threewaycalling = no',
         'hasdirectory = no',
         'callwaiting = no',
         'hasmanager = no',
         'hasagent = no',
         'hassip = yes',
         'hasiax = yes',
         'secret = {passwd}',
         'nat = yes',
         'canreinvite = no',
         'dtmfmode = rfc2833',
         'insecure = no',
         'pickupgroup = 1',
         '\n',
         'macaddress = {sip}',
         'autoprov = yes',
         'label = {sip}',
         'linenumber = 1',
         'LINEKEYS = 1',
         'disallow = all',
         'allow = ulaw,gsm']
passwrd = ['rMu8TGqPR', 'cFQZCQa3r', 'AtkGgyDmU', 'PzbtinYj4', 'RXHwNhd4o', 'aVw4m8fn6', 'T7CaoqUJv', 'pTPUrgqhu',
           'ZxBNzyYkC', 'vEBYxb56a', 'RuYw32xaH', 'pX5MBB7tz', 'Na8oN8u7e', 'hFYkis2nH', 't7n9Mg4QX', 'bEhZ6MZJj',
           'Qich9ZzqG', 'FikDF4wjT', '5gcmfqn2P', 'uEUW9WT9y', 'wuZxBCzGJ', 'h6YqcxGN6', '5NRPqBxHE', 'ojmYX2tJv',
           'Q2aJV5H9m', '2bm8M2i66', '9B4KFpe8h', '9tENyvPz8', '9QYsCDdrd', 'NhqH3X4uU', 'C5cmLEk5v', 'vZ4BcFqTo',
           'ZZa6WZzCz', 't55rd2ksC', 'TYBo4DP6c', 'ZVxrqzahx', 'jGQ6z5P7r', 'ouhsQzj3N', 'eWHFsGnZn', 'ZTvwZGsLL',
           'aXhPKCWxs', 'RDUwhk6aS', 'Vtu66i7J2', '9fjTPy3AU', 'NQYEBVxf5', '7jyqS8eZ6', '34VSkQxAe', 'tcUhuxrc6',
           'jEi974DiM', 'VDxWqZvtV', 'mGatbAmdk', 'Ma4FRay7h', 'JojxatbGW', 'LDFHvoYRj', 'HZ8dxqWdG', '6c9z2eT6y',
           'k8NExfrUA', 'HSc6xPdNj', 'DAuZSbePe', 'd3dekRajv', 'QJCJwti93', 'Sc8XwsohV', '9nkYuAog8', 'JDojCSAoy',
           'LCThbbQyX', 'Ay3LYGWNq', 'EffwTgsfH', '9JYubfCw9', 'JuNxppLGQ', '8TpKzbw8N', '6UsvTTUia', 'n6XzXHbyW',
           'nB2aJmdSJ', 'Nu3qnwoeC', 'FKERSfhNg', 'Kzwk48fLL', 'gmAGs6DNQ', 'QCDxoKAHZ', '2Do7gmb2c', 'ccMLbtmTH',
           'hyPKabZyY', 'pf4avmEga', 'df33aapEU', 'TnosNCpPd', '7TTQJhcef', 'cVCB2ee5J', 'X7HEpYsyd', '8mQRf4DSD',
           'vocYqctFL', 'VhRYK7Umi', 'f3t2tw8Yd', 'gFCv6kJsH', 'euBsiqQsn', 'WCUmKWyVt', 'Yagm7q3SX', 'QpveSzVWk',
           'Za6ASvRm4', 'wLrYDeBaU', 'f2XX8f68D']
counter = 0
startrange = 601
for i in range(startrange, (startrange+99)):
    print('\n'.join(templ).format(sip=i, passwd=passwrd[counter]))
    counter += 1
